% member5_app_frontend/DristhiSetu.m
function fig = DristhiSetu
    % =========================================================================
    % 0. PATH LINKING & MODEL LOADING
    % =========================================================================
    thisFile = mfilename('fullpath');
    [currentFolder, ~, ~] = fileparts(thisFile);
    projectRoot = fileparts(currentFolder);
    if isempty(projectRoot), projectRoot = pwd; end
    addpath(genpath(projectRoot));
    warning('off', 'MATLAB:ui:figure:Scrollable');
    
    MODEL_PRIMARY_PATH = 'D:\EyeTriage_Prototype (1)\EyeTriage_Prototype\DR_Project\models\Model1_ResNet18\ResNet18_EyePACS.mat';
    MODEL_FALLBACK_PATH = fullfile(projectRoot, 'DR_Project', 'models', 'Model1_ResNet18', 'ResNet18_EyePACS.mat');
    
    targetModelPath = "";
    if isfile(MODEL_PRIMARY_PATH)
        targetModelPath = MODEL_PRIMARY_PATH;
    elseif isfile(MODEL_FALLBACK_PATH)
        targetModelPath = MODEL_FALLBACK_PATH;
    end
    
    dlNet = [];
    classNames = ["Grade_0", "Grade_1", "Grade_2", "Grade_3", "Grade_4"];
    if targetModelPath ~= ""
        try
            loaded = load(targetModelPath);
            if isfield(loaded, 'netEyePACS'), dlNet = loaded.netEyePACS;
            elseif isfield(loaded, 'net'),     dlNet = loaded.net; end
            if isfield(loaded, 'CLASS_NAMES'), classNames = loaded.CLASS_NAMES; end
            fprintf('[DristhiSetu] ResNet-18 model ready: %s\n', targetModelPath);
        catch ME
            warning('[DristhiSetu] Model load failure: %s', ME.message);
        end
    end

    % =========================================================================
    % 1. UI SETUP & APPLICATION STATE
    % =========================================================================
    fig = uifigure('Name', 'DristhiSetu AI - Retinal Diagnostic Copilot', ...
        'Position', [50, 40, 1000, 720], 'Color', [0.08, 0.09, 0.11], ...
        'Scrollable', 'off', 'Visible', 'on');
    
    state = struct('raw', [], 'clean', [], 'diag', "Unscreened", ...
                   'isChatActive', false, 'imgPath', "", 'imgName', "");
               
    % Cache container for active report export
    lastReportPayload = [];
               
    feedHTML = uihtml(fig, 'Position', [40, 140, 920, 545], 'Visible', 'off');
    feedHTML.HTMLSource = getFeedHTML();
    feedHTML.DataChangedFcn = @(s, e) handleFeedEvents(s.Data);
    
    lblHero = uilabel(fig, 'Position', [100, 420, 800, 55], 'Text', 'DristhiSetu AI', ...
        'FontSize', 34, 'FontWeight', 'bold', 'FontColor', [0.90, 0.92, 0.96], 'HorizontalAlignment', 'center');
    lblSubHero = uilabel(fig, 'Position', [100, 385, 800, 25], ...
        'Text', 'Attach Retinal Fundus Scan & Enter Prompt to Begin', ...
        'FontSize', 13.5, 'FontColor', [0.48, 0.55, 0.65], 'HorizontalAlignment', 'center');
        
    capsuleHTML = uihtml(fig, 'Position', [130, 230, 740, 135]);
    capsuleHTML.HTMLSource = getCapsuleHTML();
    capsuleHTML.DataChangedFcn = @(s, e) handleAction(s.Data);

    % =========================================================================
    % 2. EVENT CONTROLLERS
    % =========================================================================
    function handleFeedEvents(data)
        if isempty(data) || ~isfield(data, 'action'), return; end
        if strcmp(data.action, 'download_pdf') && ~isempty(lastReportPayload)
            try
                pdfFile = generate_clinical_pdf(lastReportPayload);
                uialert(fig, sprintf('PDF Report successfully generated:\n%s', pdfFile), ...
                        'Report Export Complete', 'Icon', 'success');
            catch ME
                uialert(fig, sprintf('PDF Export error: %s', ME.message), ...
                        'Export Failed', 'Icon', 'error');
            end
        end
    end

    function handleAction(data)
        if isempty(data) || ~isfield(data, 'action'), return; end
        switch data.action
            case 'attach'
                selectScan();
            case 'clear_attachment'
                state.raw = []; state.imgPath = ""; state.imgName = "";
            case 'send'
                processPipeline(string(data.text));
        end
    end

    function selectScan()
        [fName, fPath] = uigetfile({'*.jpg;*.jpeg;*.png;*.tif;*.bmp', 'Retinal Scans'}, 'Select Retinal Fundus Scan');
        if isequal(fName, 0), return; end
        
        state.imgPath = string(fullfile(fPath, fName));
        state.imgName = string(fName);
        raw = imread(fullfile(fPath, fName));
        if ndims(raw) == 2, raw = repmat(raw, 1, 1, 3); elseif size(raw, 3) > 3, raw = raw(:,:,1:3); end
        state.raw = imresize(raw, [584 565]);
        
        thumb = imresize(state.raw, [48 48]);
        capsuleHTML.Data = struct('event', 'image_attached', ...
                                  'b64', "data:image/png;base64," + imgToBase64(thumb), ...
                                  'filename', string(fName));
    end

    function processPipeline(q)
        q = strtrim(q);
        hasImage = ~isempty(state.raw);
        if q == "" && ~hasImage, return; end
        if q == "" && hasImage, q = "Analyze this scan and classify diabetic retinopathy grade."; end
        
        activateChat();
        if hasImage
            userSnippet = sprintf('<div class="msg-user">📎 <b>%s</b><br/>%s</div>', state.imgName, q);
        else
            userSnippet = sprintf('<div class="msg-user">%s</div>', q);
        end
        
        if ~hasImage
            reply = formatGeminiResponse(queryGeminiAgent(q));
            feedHTML.Data = struct('newHtml', string(userSnippet) + sprintf('<div class="msg-ai"><div class="sparkle-icon">✦</div><div>%s</div></div>', reply), 'timestamp', posixtime(datetime('now')));
            return;
        end
        
        % 1. Call Member3 Enhanced_Image.m
        state.clean = Enhanced_Image(state.raw);
        
        % 2. Call Member3 Access_Quality_Local.m
        [passed, sharpVal, contVal] = Access_Quality_Local(state.clean, 22.0, 0.35);
        
        if ~passed
            aiSnippet = string([ ...
                '<div class="msg-ai"><div class="sparkle-icon">✦</div><div class="report-card" style="border-color: rgba(239,68,68,0.5);">' ...
                '<span class="badge badge-danger">Quality Rejected</span>' ...
                '<p style="margin-top:8px; font-size:13px; color:#cbd5e1;">Scan sharpness (<b>' num2str(sharpVal, '%.1f') '</b>) or contrast (<b>' num2str(contVal, '%.2f') '</b>) is below clinical thresholds. Please recapture.</p>' ...
                '</div></div>']);
            feedHTML.Data = struct('newHtml', string(userSnippet) + string(aiSnippet), 'timestamp', posixtime(datetime('now')));
            return;
        end
        
        % 3. Call Member3 extract_biomarkers.m
        [masks, overlayResult, cvMetrics] = extract_biomarkers(state.clean);
        
        % 4. Call Member4 predict_resnet18.m
        [cnnClass, cnnConf, cnnOk] = predict_resnet18(dlNet, state.clean, classNames);
        
        % 5. Hybrid Clinical Decision Gate
        if cvMetrics.neovascular_risk
            gradeStr = "Level 4 – Proliferative DR (PDR)"; refTag = "EMERGENCY (Immediate)"; badgeClass = "badge-danger";
        elseif cvMetrics.foveal_threat || cvMetrics.hemorrhages_count > 10 || cvMetrics.exudates_count > 15
            gradeStr = "Level 3 – Severe NPDR"; refTag = "YES (Urgent)"; badgeClass = "badge-danger";
        elseif cnnOk
            switch cnnClass
                case "Grade_0", gradeStr = "Level 0 – No Diabetic Retinopathy"; refTag = "NO"; badgeClass = "badge-success";
                case "Grade_1", gradeStr = "Level 1 – Mild NPDR"; refTag = "NO (Annual Monitoring)"; badgeClass = "badge-info";
                case "Grade_2", gradeStr = "Level 2 – Moderate NPDR"; refTag = "YES"; badgeClass = "badge-alert";
                case "Grade_3", gradeStr = "Level 3 – Severe NPDR"; refTag = "YES (Urgent)"; badgeClass = "badge-danger";
                case "Grade_4", gradeStr = "Level 4 – Proliferative DR (PDR)"; refTag = "EMERGENCY (Immediate)"; badgeClass = "badge-danger";
                otherwise,      gradeStr = string(cnnClass); refTag = "REFERRAL REQUIRED"; badgeClass = "badge-alert";
            end
        else
            gradeStr = "Level 2 – Moderate NPDR"; refTag = "YES"; badgeClass = "badge-alert";
        end
        
        % 6. Render Colored Visual Strips
        % NEW (Clear, High-Contrast Clinical Masks)
        grayClean = rgb2gray(state.clean);
        bgClear = repmat(imadjust(grayClean, stretchlim(grayClean), [0.15 0.70]), 1, 1, 3);
        
        % Dilate punctate micro-lesions slightly so they pop out clearly on A4 print
        maskEx_plot  = imdilate(masks.exudates, strel('disk', 1));
        maskMA_plot  = imdilate(masks.ma, strel('disk', 2));
        maskHem_plot = imdilate(masks.hem, strel('disk', 1));
        maskFov_plot = imdilate(bwperim(masks.fovea), strel('disk', 2));
        
        imgEx  = Colorize_Image(bgClear, maskEx_plot,  [255, 220, 0]);   % Vivid Yellow
        imgMA  = Colorize_Image(bgClear, maskMA_plot,  [255, 30, 30]);    % Vivid Red
        imgHem = Colorize_Image(bgClear, maskHem_plot, [240, 0, 140]);   % Vivid Magenta
        imgFov = Colorize_Image(bgClear, maskFov_plot, [0, 150, 255]);   % Vivid Blue
        
        b64_raw = imgToBase64(state.raw);
        b64_seg = imgToBase64(overlayResult);
        b64_ex  = imgToBase64(imgEx);
        b64_ma  = imgToBase64(imgMA);
        b64_hem = imgToBase64(imgHem);
        b64_fov = imgToBase64(imgFov);
        
        % 7. Gemini Synchronization
        foveaStr = "No"; if cvMetrics.foveal_threat, foveaStr = "YES (High Risk)"; end
        lQuery = sprintf(['Biomarkers: %d exudates, %d microaneurysms, %d hemorrhages. ' ...
                          'Foveal threat: %s. Neovascular: %s. Prompt: %s'], ...
                          cvMetrics.exudates_count, cvMetrics.microaneurysms_count, cvMetrics.hemorrhages_count, ...
                          foveaStr, string(cvMetrics.neovascular_risk), q);
                      
        if state.imgPath ~= "" && exist(state.imgPath, 'file') == 2
            suggestionsRaw = queryGeminiAgent(gradeStr, lQuery, char(state.imgPath));
        else
            suggestionsRaw = queryGeminiAgent(gradeStr, lQuery);
        end
        suggestionsHtml = formatGeminiResponse(suggestionsRaw);
        
        % Cache payload for PDF generation
        lastReportPayload = struct( ...
            'imgName', state.imgName, ...
            'gradeStr', gradeStr, ...
            'refTag', refTag, ...
            'cnnConf', cnnConf, ...
            'sharpVal', sharpVal, ...
            'contVal', contVal, ...
            'numEx', cvMetrics.exudates_count, ...
            'numMA', cvMetrics.microaneurysms_count, ...
            'numHem', cvMetrics.hemorrhages_count, ...
            'foveaStr', foveaStr, ...
            'isNeovasc', cvMetrics.neovascular_risk, ...
            'rawImg', state.raw, ...
            'overlayImg', overlayResult, ...
            'imgEx', imgEx, ...
            'imgMA', imgMA, ...
            'imgHem', imgHem, ...
            'imgFov', imgFov, ...
            'guidanceHtml', suggestionsHtml ...
        );
        
        % 8. Render UI Assessment Card with Download Action Button
        aiSnippet = string([ ...
            '<div class="msg-ai">' ...
            '  <div class="sparkle-icon">✦</div>' ...
            '  <div class="report-card">' ...
            '    <div style="display:flex; justify-content:space-between; align-items:center; border-bottom:1px solid rgba(255,255,255,0.08); padding-bottom:10px;">' ...
            '      <div><span style="font-size:16px; font-weight:700; color:#f8fafc;">Retinal Diagnostic Assessment</span></div>' ...
            '      <div style="display:flex; gap:8px;">' ...
            '        <span class="badge badge-success">Quality: Passed</span>' ...
            '        <span class="badge ' char(badgeClass) '">' char(gradeStr) '</span>' ...
            '        <span class="badge ' char(badgeClass) '">Referral: ' char(refTag) '</span>' ...
            '      </div>' ...
            '    </div>' ...
            '    <div style="font-size:12.5px; color:#94a3b8; margin:8px 0 12px 0;">ResNet-18 Confidence: <b style="color:#38bdf8;">' num2str(cnnConf, '%.1f') '%</b> | Sharpness: <b>' num2str(sharpVal, '%.1f') '</b> | Contrast: <b>' num2str(contVal, '%.2f') '</b></div>' ...
            '    <div class="grid-images">' ...
            '      <div class="img-wrapper"><div class="img-label">1. Original Input Fundus</div><img class="scan-img" src="data:image/png;base64,' char(b64_raw) '"/></div>' ...
            '      <div class="img-wrapper"><div class="img-label">2. Multi-Biomarker Overlay</div><img class="scan-img" src="data:image/png;base64,' char(b64_seg) '"/></div>' ...
            '    </div>' ...
            '    <div class="grid-biomarkers">' ...
            '      <div class="bio-wrapper"><div class="bio-label" style="color:#fbbf24;">Exudates (' num2str(cvMetrics.exudates_count) ')</div><img class="bio-img" src="data:image/png;base64,' char(b64_ex) '"/></div>' ...
            '      <div class="bio-wrapper"><div class="bio-label" style="color:#f43f5e;">Microaneurysms (' num2str(cvMetrics.microaneurysms_count) ')</div><img class="bio-img" src="data:image/png;base64,' char(b64_ma) '"/></div>' ...
            '      <div class="bio-wrapper"><div class="bio-label" style="color:#e11d48;">Hemorrhages (' num2str(cvMetrics.hemorrhages_count) ')</div><img class="bio-img" src="data:image/png;base64,' char(b64_hem) '"/></div>' ...
            '      <div class="bio-wrapper"><div class="bio-label" style="color:#38bdf8;">Macular Threat (' char(foveaStr) ')</div><img class="bio-img" src="data:image/png;base64,' char(b64_fov) '"/></div>' ...
            '    </div>' ...
            '    <div class="lesion-box">' ...
            '      <div class="lesion-item"><span>Hard Exudates (Lipid/Fluid Leaks)</span><b style="color:#fbbf24;">' num2str(cvMetrics.exudates_count) ' detected</b></div>' ...
            '      <div class="lesion-item"><span>Microaneurysms (Capillary Swellings)</span><b style="color:#f43f5e;">' num2str(cvMetrics.microaneurysms_count) ' detected</b></div>' ...
            '      <div class="lesion-item"><span>Hemorrhages (Internal Bleeding)</span><b style="color:#e11d48;">' num2str(cvMetrics.hemorrhages_count) ' detected</b></div>' ...
            '      <div class="lesion-item"><span>Macular/Foveal Threat</span><b style="color:#38bdf8;">' char(foveaStr) '</b></div>' ...
            '    </div>' ...
            '    <div style="font-size:12px; font-weight:600; color:#94a3b8; text-transform:uppercase; margin-bottom:6px;">Clinical Guidance & Suggestions:</div>' ...
            '    <div class="advice-box">' char(suggestionsHtml) '</div>' ...
            '    ' ...
            '    <!-- PDF Report Export Action Button -->' ...
            '    <div style="margin-top:16px; display:flex; justify-content:flex-end;">' ...
            '      <button class="btn-pdf-export" onclick="window.triggerPdfExport()">📥 Download Clinical Report (PDF)</button>' ...
            '    </div>' ...
            '  </div>' ...
            '</div>' ...
        ]);
        
        feedHTML.Data = struct('newHtml', string(userSnippet) + string(aiSnippet), 'timestamp', posixtime(datetime('now')));
        capsuleHTML.Data = struct('event', 'reset_attachment');
    end

    % =========================================================================
    % 3. UI TEMPLATES & HELPERS
    % =========================================================================
    function activateChat()
        if ~state.isChatActive
            state.isChatActive = true;
            lblHero.Visible = 'off'; lblSubHero.Visible = 'off';
            feedHTML.Visible = 'on';
            set(capsuleHTML, 'Position', [130, 10, 740, 135]);
            drawnow;
        end
    end
    
    function b64 = imgToBase64(imgMatrix)
        tempF = [tempname, '.png']; imwrite(imgMatrix, tempF);
        fid = fopen(tempF, 'rb'); rawBytes = fread(fid, inf, 'uint8=>uint8'); fclose(fid); delete(tempF);
        b64 = string(matlab.net.base64encode(rawBytes));
    end
    
    function formatted = formatGeminiResponse(rawText)
        formatted = regexprep(string(rawText), '\*\*(.*?)\*\*', '<b>$1</b>');
        formatted = regexprep(formatted, '(\r\n|\n|\r)', '<br/>');
    end

    function s = getFeedHTML()
        s = ['<!DOCTYPE html><html><head><meta charset="utf-8"/><style>' ...
             '* { box-sizing: border-box; margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; }' ...
             'html { height: 100%; overflow-y: auto; background-color: #14171c; }' ...
             'body { background-color: #14171c; color: #e2e8f0; padding: 20px 24px 80px 24px; min-height: 100%; }' ...
             '::-webkit-scrollbar { width: 8px; } ::-webkit-scrollbar-track { background: #14171c; } ::-webkit-scrollbar-thumb { background: #2a2e39; border-radius: 4px; }' ...
             '.msg-container { display: flex; flex-direction: column; gap: 16px; width: 100%; max-width: 860px; margin: 0 auto; }' ...
             '.msg-user { align-self: flex-end; background: #1e293b; border: 1px solid rgba(255,255,255,0.08); padding: 12px 18px; border-radius: 18px 18px 4px 18px; font-size: 13.5px; max-width: 75%; }' ...
             '.msg-ai { align-self: flex-start; display: flex; gap: 12px; width: 100%; }' ...
             '.sparkle-icon { color: #38bdf8; font-size: 20px; line-height: 1; margin-top: 4px; flex-shrink: 0; }' ...
             '.report-card { background: #181c24; border: 1px solid rgba(59, 130, 246, 0.25); border-radius: 16px; padding: 20px; width: 100%; box-shadow: 0 4px 25px rgba(0,0,0,0.4); }' ...
             '.badge { display: inline-block; padding: 4px 10px; border-radius: 9999px; font-size: 11px; font-weight: bold; }' ...
             '.badge-danger { background: rgba(239, 68, 68, 0.15); color: #f87171; border: 1px solid rgba(239,68,68,0.3); }' ...
             '.badge-alert { background: rgba(245, 158, 11, 0.15); color: #fbbf24; border: 1px solid rgba(245,158,11,0.3); }' ...
             '.badge-success { background: rgba(16, 185, 129, 0.15); color: #34d399; border: 1px solid rgba(16,185,129,0.3); }' ...
             '.badge-info { background: rgba(56, 189, 248, 0.15); color: #38bdf8; border: 1px solid rgba(56,189,248,0.3); }' ...
             '.grid-images { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin: 16px 0 10px 0; }' ...
             '.img-wrapper { background: #0f131a; border-radius: 12px; padding: 8px; border: 1px solid rgba(255,255,255,0.06); text-align: center; }' ...
             '.img-label { font-size: 11.5px; font-weight: 600; color: #94a3b8; text-transform: uppercase; margin-bottom: 6px; }' ...
             '.scan-img { width: 100%; height: auto; border-radius: 8px; display: block; }' ...
             '.grid-biomarkers { display: grid; grid-template-columns: repeat(4, 1fr); gap: 10px; margin-bottom: 16px; }' ...
             '.bio-wrapper { background: #11151e; border-radius: 8px; padding: 6px; border: 1px solid rgba(255,255,255,0.05); text-align: center; }' ...
             '.bio-label { font-size: 10px; font-weight: 600; color: #94a3b8; text-transform: uppercase; margin-bottom: 4px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }' ...
             '.bio-img { width: 100%; height: auto; border-radius: 6px; display: block; border: 1px solid rgba(255,255,255,0.06); }' ...
             '.lesion-box { background: #11141a; border-radius: 10px; padding: 12px; font-size: 13px; margin-bottom: 14px; }' ...
             '.lesion-item { display: flex; justify-content: space-between; padding: 5px 0; border-bottom: 1px solid rgba(255,255,255,0.05); }' ...
             '.advice-box { background: #131b28; border-left: 3px solid #38bdf8; border-radius: 0 10px 10px 0; padding: 12px 14px; font-size: 12.5px; line-height: 1.6; color: #cbd5e1; }' ...
             '.btn-pdf-export { background: linear-gradient(135deg, #0284c7, #0369a1); color: #ffffff; border: 1px solid rgba(56,189,248,0.4); padding: 8px 18px; border-radius: 8px; font-size: 12.5px; font-weight: 600; cursor: pointer; transition: all 0.2s ease; display: inline-flex; align-items: center; gap: 6px; }' ...
             '.btn-pdf-export:hover { background: linear-gradient(135deg, #0369a1, #075985); box-shadow: 0 0 12px rgba(56,189,248,0.4); transform: translateY(-1px); }' ...
             '</style></head><body><div class="msg-container" id="msgThread"></div>' ...
             '<script>' ...
             '  let htmlCompRef = null;' ...
             '  function setup(htmlComponent) {' ...
             '    htmlCompRef = htmlComponent;' ...
             '    htmlComponent.addEventListener("DataChanged", function(event) {' ...
             '      if (!htmlComponent.Data) return;' ...
             '      const thread = document.getElementById("msgThread");' ...
             '      thread.innerHTML += htmlComponent.Data.newHtml;' ...
             '      setTimeout(() => { window.scrollTo({ top: document.body.scrollHeight, behavior: "smooth" }); }, 50);' ...
             '    });' ...
             '  }' ...
             '  window.triggerPdfExport = function() {' ...
             '    if (htmlCompRef) {' ...
             '      htmlCompRef.Data = { action: "download_pdf", timestamp: Date.now() };' ...
             '    }' ...
             '  };' ...
             '</script>' ...
             '</body></html>'];
    end
    
    function s = getCapsuleHTML()
        s = ['<!DOCTYPE html><html><head><meta charset="utf-8"/><style>' ...
             '* { box-sizing: border-box; margin: 0; padding: 0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; }' ...
             'html, body { background-color: #14171c !important; overflow: hidden; display: flex; flex-direction: column; align-items: center; justify-content: flex-end; height: 100vh; width: 100vw; padding-bottom: 8px; }' ...
             '.capsule-wrapper { position: relative; width: 100%; display: flex; flex-direction: column; align-items: center; }' ...
             '.preview-bar { display: none; align-items: center; gap: 8px; background: #1e2533; border: 1px solid rgba(56, 189, 248, 0.35); padding: 5px 12px; border-radius: 10px; margin-bottom: 8px; align-self: flex-start; margin-left: 20px; }' ...
             '.preview-thumb { width: 32px; height: 32px; border-radius: 6px; object-fit: cover; border: 1px solid rgba(255,255,255,0.2); }' ...
             '.preview-text { font-size: 12px; color: #93c5fd; max-width: 220px; white-space: nowrap; overflow: hidden; text-overflow: ellipsis; font-weight: 500; }' ...
             '.btn-remove { background: transparent; border: none; color: #94a3b8; cursor: pointer; font-size: 14px; margin-left: 6px; }' ...
             '.btn-remove:hover { color: #f87171; }' ...
             '.capsule-container { position: relative; z-index: 2; display: flex; align-items: center; width: 100%; height: 52px; background: #1b1e26; border: 1.2px solid rgba(75, 110, 175, 0.38); border-radius: 9999px; padding: 6px 14px; box-shadow: 0 4px 20px rgba(0,0,0,0.6); }' ...
             '.capsule-container:focus-within { border-color: #3b82f6; box-shadow: 0 0 20px rgba(59, 130, 246, 0.45); }' ...
             '.btn-icon { background: transparent; border: none; outline: none; cursor: pointer; color: #94a3b8; font-size: 19px; width: 38px; height: 38px; border-radius: 50%; display: flex; align-items: center; justify-content: center; }' ...
             '.btn-icon:hover { color: #60a5fa; background: rgba(255,255,255,0.06); }' ...
             '.prompt-input { flex: 1; background: transparent; border: none; outline: none; color: #f8fafc; font-size: 14px; padding: 0 12px; }' ...
             '.btn-send { background: linear-gradient(135deg, #2563eb, #1d4ed8); color: #fff; border: none; outline: none; width: 38px; height: 38px; border-radius: 50%; font-size: 14px; cursor: pointer; display: flex; align-items: center; justify-content: center; box-shadow: 0 0 10px rgba(37,99,235,0.4); }' ...
             '</style></head><body>' ...
             '<div class="capsule-wrapper">' ...
             '  <div class="preview-bar" id="previewBar"><img class="preview-thumb" id="previewImg"/><span class="preview-text" id="previewName"></span><button class="btn-remove" id="removeBtn">✕</button></div>' ...
             '  <div class="capsule-container"><button class="btn-icon" id="attachBtn">＋</button><input class="prompt-input" id="promptText" type="text" placeholder="Upload retinal scan & type instructions..."/><button class="btn-send" id="sendBtn">➤</button></div>' ...
             '</div>' ...
             '<script>function setup(c){const a=document.getElementById("attachBtn"),s=document.getElementById("sendBtn"),r=document.getElementById("removeBtn"),p=document.getElementById("promptText"),b=document.getElementById("previewBar"),i=document.getElementById("previewImg"),n=document.getElementById("previewName");' ...
             'function snd(){const v=p.value;p.value="";c.Data={action:"send",text:v,timestamp:Date.now()};}' ...
             'a.addEventListener("click",()=>{c.Data={action:"attach",timestamp:Date.now()};});' ...
             'r.addEventListener("click",()=>{b.style.display="none";c.Data={action:"clear_attachment",timestamp:Date.now()};});' ...
             's.addEventListener("click",snd);p.addEventListener("keydown",(e)=>{if(e.key==="Enter")snd();});' ...
             'c.addEventListener("DataChanged",()=>{if(c.Data&&c.Data.event==="image_attached"){i.src=c.Data.b64;n.innerText=c.Data.filename;b.style.display="inline-flex";}else if(c.Data&&c.Data.event==="reset_attachment"){b.style.display="none";}});}' ...
             '</script></body></html>'];
    end
end